const express = require('express');
const cors = require('cors');
const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs').promises;
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static('.'));

// API endpoint to clone website
app.post('/api/clone', async (req, res) => {
  try {
    const { url, fileName } = req.body;
    
    if (!url) {
      return res.status(400).json({ error: 'URL is required' });
    }
    
    // Fetch website content
    const response = await axios.get(url, {
      timeout: 10000,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
      }
    });
    
    const htmlContent = response.data;
    
    // Process HTML with Cheerio
    const $ = cheerio.load(htmlContent);
    
    // Convert relative URLs to absolute URLs
    const baseUrl = new URL(url).origin;
    
    $('img[src^="/"], link[href^="/"], script[src^="/"], a[href^="/"]').each((i, elem) => {
      const $elem = $(elem);
      const attrName = $elem.is('img') || $elem.is('script') ? 'src' : 'href';
      const relativeUrl = $elem.attr(attrName);
      if (relativeUrl && relativeUrl.startsWith('/')) {
        $elem.attr(attrName, baseUrl + relativeUrl);
      }
    });
    
    // Add cloning information header
    const header = `<!-- 
  This page was cloned from: ${url}
  Cloned at: ${new Date().toISOString()}
  Generated by Website Cloner Tool
-->
`;
    
    const processedHtml = header + $.html();
    
    // Generate filename
    const finalFileName = fileName || generateFileName(url);
    const filePath = path.join(__dirname, `${finalFileName}.html`);
    
    // Save file
    await fs.writeFile(filePath, processedHtml, 'utf8');
    
    res.json({
      success: true,
      fileName: `${finalFileName}.html`,
      message: 'Website successfully cloned',
      url: `/${finalFileName}.html`
    });
    
  } catch (error) {
    console.error('Error cloning website:', error);
    res.status(500).json({
      error: 'Failed to clone website',
      details: error.message
    });
  }
});

// Get list of cloned files
app.get('/api/cloned-files', async (req, res) => {
  try {
    const files = await fs.readdir(__dirname);
    const htmlFiles = files
      .filter(file => file.startsWith('cloned_') && file.endsWith('.html'))
      .map(file => ({
        name: file,
        url: `/${file}`,
        created: new Date().toISOString() // You could get actual file stats
      }));
    
    res.json(htmlFiles);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get cloned files' });
  }
});

function generateFileName(url) {
  try {
    const domain = new URL(url).hostname.replace(/^www\./, '');
    const timestamp = new Date().toISOString().slice(0, 19).replace(/[T:]/g, '_');
    return `cloned_${domain.replace(/\./g, '_')}_${timestamp}`;
  } catch {
    const timestamp = new Date().toISOString().slice(0, 19).replace(/[T:]/g, '_');
    return `cloned_website_${timestamp}`;
  }
}

app.listen(PORT, () => {
  console.log(`Website Cloner server running on http://localhost:${PORT}`);
});
